PKG_NAME = libexif
PKG_VERS = 0.6.21
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://sourceforge.net/projects/libexif/files/libexif/0.6.21/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://sourceforge.net/projects/libexif/
COMMENT  = The EXIF library allows you to parse an EXIF file and read the data from tags written by digital cameras to jpeg files
LICENSE  = (LGPLv2)

GNU_CONFIGURE = 1
CONFIGURE_ARGS = 

include ../../mk/spksrc.cross-cc.mk

